digestif/urls.py
from django.conf.urls import url
from . import views
# from .utils.populate_conclusionPages import populate

# populate() # populate the explore page

app_name = 'digestif'
urlpatterns = [
    # /digestif/
    url(r'^$', views.index, name='index'),
    #/digestif/explore/cp_id/
    url(r'^explore/(?P<id>cp_[a-z]*_[a-z]*)/$', views.cp_detail, name='cp_detail'),
    #/digestif/explore/block_id/
    url(r'^explore/(?P<id>block_[a-z]*_[a-z]*)/$', views.block_detail, name='block_detail'),
    # /digestif/explore/
    url(r'explore/$', views.explore, name='explore'),
    # /digestif/create/
    url(r'create/$', views.create, name='create'),
]

digestifProject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include

urlpatterns = [
    url(r'^digestif/', include('digestif.urls')),
    url(r'^admin/', admin.site.urls),
]

digestif/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from jsonfield import JSONField
from django.utils.encoding import python_2_unicode_compatible

# Includes all the meta-data for a conclusion page
# Also stores the file name to the static image associated with the full conclusion page
# Also stores references to the Blocks that store more detailed information and comprise the conclusion page
@python_2_unicode_compatible
class Block(models.Model):
    # block_id = models.CharField(max_length=255, primary_key=True)
    block_type = models.CharField(max_length=100)
    path_name = models.CharField(max_length=200)
    # block_layout = models.CharField(max_length=50)
    content = models.TextField()
    # benefits = models.CharField(max_length=500)
    cp = models.ForeignKey('ConclusionPage')
    """
    block_type refers to the kind of block that it is (e.g., Acknowledgements, Research Goals, etc.)
    path_name refers to the image of the particular block
    content is the HTML describing this block
    cp refers to the ConclusionPage object to which this Block points (Conclusion page it is associated with)
    """

    def __str__(self):
        return "%s" % self.block_type

    def __repr__(self):
        return "%s" % self.block_type



class ConclusionPage(models.Model):
    cp_id = models.CharField(max_length=200, primary_key=True) # used as a primary key
    platform = models.CharField(max_length=200)
    study = models.CharField(max_length=500)

    # let's try not grouping the blocks together in a JSON for now...
    full_page = models.CharField(max_length=200)
    # acknowledgements = models.ForeignKey('Block', on_delete=models.CASCADE,)
    # research_purpose = models.ForeignKey('Block', on_delete=models.CASCADE,)
    # study_summary = models.ForeignKey('Block', on_delete=models.CASCADE,)
    # score_interpretation = models.ForeignKey('Block', on_delete=models.CASCADE,)
    # personalized_results = models.ForeignKey('Block', on_delete=models.CASCADE,)
    # social_comparison = models.ForeignKey('Block', on_delete=models.CASCADE,)
    # share = models.ForeignKey('Block', on_delete=models.CASCADE,)
    # feedback = models.ForeignKey('Block', on_delete=models.CASCADE,)
    # other_studies = models.ForeignKey('Block', on_delete=models.CASCADE,)
    # additional_resources = models.ForeignKey('Block', on_delete=models.CASCADE,)
    content = models.TextField()

    """
    cp_id refers to the primary key id used for this conclusion page instance
    platform refers to the name of the online experimentation platform the conclusion page comes from
    study refers to the study on the "platform" this conclusion page comes from
    full_page is a string to the path name of the full conclusion page image file
    ALL OTHERS are references to the Block models that encapsulate information about the
        individual blocks comprising a full conclusion page (see Block model below)
    """

    blocks = models.ManyToManyField(Block)

    """
    blocks encapsulates all the ForeignKey Blocks that could be part of a Conclusion Page.
    blocks includes
        acknowledgements
        research_purpose
        study_summary
        score_interpretation
        personalized_results
        social_comparison
        share
        feedback
        other_studies
        additional_resources
    """

    def __str__(self):
        # return ",".join(b.block_type for b in self.blocks.all())
        return "%s" % self.cp_id

    def __repr__(self):
        # return "," .join(b.block_type for b in self.blocks.all())
        return "%s" % self.cp_id

digestif/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

from .models import ConclusionPage
from .models import Block
from .utils.populate_cp_blocks import populate # populate the DB with full conclusion pages and blocks
# from .utils.populate_favorites import getFavorites
import json

# global variable so that database is populated only once (to avoid duplicates)
# already_populated = 0;

def index(request):
    return render(request, 'digestif/index.html') # show just plain index page

def explore(request):
    populate()
    conclusion_pages = ConclusionPage.objects.order_by('platform') # get ConclusionPages ordered by platform name
    platforms = ConclusionPage.objects.order_by('platform').values('platform').distinct() # get unique set of platforms
    acknowledgments = Block.objects.filter(block_type='acknowledgments')
    community_building = Block.objects.filter(block_type='community_building')
    experimental_design = Block.objects.filter(block_type='experimental_design')
    feedback = Block.objects.filter(block_type='feedback')
    other_studies = Block.objects.filter(block_type='other_studies')
    personalized_results = Block.objects.filter(block_type='personalized_results')
    previous_research = Block.objects.filter(block_type='previous_research')
    research_goals = Block.objects.filter(block_type='research_goals')
    research_motivations = Block.objects.filter(block_type='research_motivations')
    share = Block.objects.filter(block_type='share')
    context = {'conclusion_pages' : conclusion_pages, 'platforms' : platforms,
                'acknowledgments' : acknowledgments, 'community_building' : community_building,
                'experimental_design' : experimental_design, 'feedback' : feedback,
                'other_studies' : other_studies, 'personalized_results' : personalized_results,
                'previous_research' : previous_research, 'research_goals' : research_goals,
                'research_motivations' : research_motivations, 'share' : share
                }
    return render(request, 'digestif/explore.html', context)
    # return render(request, 'digestif/explore.html')

def cp_detail(request, id):
    conclusion_page = ConclusionPage.objects.get(cp_id=id)
    context = {'conclusion_page': conclusion_page}
    return render(request, 'digestif/cp_detail.html', context);

def block_detail(request, id):
    block = Block.objects.get(block_id=id)
    conclusion_page = ConclusionPage.objects.get(blocks__contains=block);
    context = {'block': block, 'conclusion_page': conclusion_page}
    return render(request, 'digestif/block_detail.html', context);

def create(request):
    # favorites = getFavorites()
    # context = {'favorites' : favorites}

    # Maybe instead of doing it in the views, I can do this directly with create.js...
    # return render(request, 'digestif/create.html', favorites)
    return render(request, 'digestif/create.html')

digestif/templates/digestif/block_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> -->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'digestif/style.css' %}">
  <!-- <script src="{% static 'digestif/detail.js' %}"></script> -->
  <title>Digestif</title>
  <script>
      function loadReel() {
        console.log('in load real function');
        // load all the thumnails here
        console.log({{block}});
      }
  </script>
</head>
<body onload="loadReel()">
  <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'digestif:index' %}">digestif</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <!-- <a class="nav-link" href="./explore.html">Explore</a> -->
                  <a class="nav-link" href="{% url 'digestif:explore' %}">Explore</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'digestif:create' %}">Create</a>
                  <!-- <a class="nav-link" href="./create.html">Create</a> -->
              </li>
          </ul>
          <span class="navbar-text">
        [dee-zhe-<span class="font-weight-bold">steef</span>]: (noun) a tool to support researchers in making their research more digestible to participants
      </span>
      </div>
  </nav>
  <br>
  <div>
    {% load static %}
    <!-- {% if conclusion_page.full_page != None %} -->
      {% with "digestif/"|add:block.path_name as path_name %}
        <div id="cpDiv" class="container">
          <div class="row">
            <!-- <div class="col-sm-1">
              have a column of small thumbnails here
              Use the pathnames somehow to create a vertical carousel of images
              Need to size the images in some way, too

            </div> -->
            <div class="col-sm-9">
              <!-- image of conclusion page -->
              <img src="{% static path_name %}" alt="Image of {{block.block_type}} from study {{conclusion_page.study}} on platform {{conclusion_page.platform}}." width="100%" />
            </div>
            <div class="col-sm-3">
              <!-- INFO -->
              <p><strong>Platform: </strong>{{conclusion_page.platform}}</p>
              <p><strong>Study: </strong>{{conclusion_page.study}}</p>
              <!-- <p><strong>Other comments: </strong>Quote or something from researcher?</p> -->
              <!-- <p>Quote or something from researcher?</p> -->
            </div>
          </div>
          <div class="clearfix">
              <!-- Do something here  underneath the columns -->
          </div>
        </div>
      {% endwith %}
    <!-- {% endif %} -->
  </div>
</body>

digestif/templates/digestif/cp_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> -->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'digestif/style.css' %}">
  <!-- <script src="{% static 'digestif/detail.js' %}"></script> -->
  <title>Digestif</title>
  <script>
      function loadReel() {
        console.log('in load real function');
        // load all the thumnails here
        console.log({{conclusion_page}});
      }
  </script>
</head>
<body onload="loadReel()">
  <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'digestif:index' %}">digestif</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <!-- <a class="nav-link" href="./explore.html">Explore</a> -->
                  <a class="nav-link" href="{% url 'digestif:explore' %}">Explore</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'digestif:create' %}">Create</a>
                  <!-- <a class="nav-link" href="./create.html">Create</a> -->
              </li>
          </ul>
          <span class="navbar-text">
        [dee-zhe-<span class="font-weight-bold">steef</span>]: (noun) a tool to support researchers in making their research more digestible to participants
      </span>
      </div>
  </nav>
  <br>
  <div>
    {% load static %}
    {% if conclusion_page.full_page != None %}
      {% with "digestif/"|add:conclusion_page.full_page as path_name %}
        <div id="cpDiv" class="container">
          <div class="row">
            <!-- <div class="col-sm-1">
              have a column of small thumbnails here
              Use the pathnames somehow to create a vertical carousel of images
              Need to size the images in some way, too

            </div> -->
            <div class="col-sm-9">
              <!-- image of conclusion page -->
              <img src="{% static path_name %}" alt="Full conclusion page from study {{conclusion_page.study}} on platform {{conclusion_page.platform}}." width="100%" />
            </div>
            <div class="col-sm-3">
              <!-- INFO -->
              <p><strong>Platform: </strong>{{conclusion_page.platform}}</p>
              <p><strong>Study: </strong>{{conclusion_page.study}}</p>
              <p><strong>Blocks used: </strong></p>
              <ul>
                {% for b in conclusion_page.blocks %}
                    <li>{{b}}</li>
                {% endfor %}
                <!-- <li><em>Block 1: </em>Explanation/benefits</li>
                <li><em>Block 2: </em>Explanation/benefits</li> -->
              </ul>
              <!-- <p><strong>Other comments: </strong>Quote or something from researcher?</p> -->
              <!-- <p>Quote or something from researcher?</p> -->
            </div>
          </div>
          <div class="clearfix">
              <!-- Do something here  underneath the columns -->
          </div>
        </div>
      {% endwith %}
    {% endif %}
  </div>
</body>

digestif/templates/digestif/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> -->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'digestif/style.css' %}">
  <!-- <script src="{% static 'digestif/detail.js' %}"></script> -->
  <title>Digestif</title>
  <script>
      function loadReel() {
        console.log('in load real function');
        // load all the thumnails here
        console.log({{conclusion_page}});
      }
  </script>
</head>
<body onload="loadReel()">
  <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'digestif:index' %}">digestif</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                  <!-- <a class="nav-link" href="./explore.html">Explore</a> -->
                  <a class="nav-link" href="{% url 'digestif:explore' %}">Explore</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'digestif:create' %}">Create</a>
                  <!-- <a class="nav-link" href="./create.html">Create</a> -->
              </li>
          </ul>
          <span class="navbar-text">
        [dee-zhe-<span class="font-weight-bold">steef</span>]: (noun) a tool to support researchers in making their research more digestible to participants
      </span>
      </div>
  </nav>
  <br>
  <div>
    {% load static %}
    {% if conclusion_page.path_names.full != None %}
      {% with "digestif/"|add:conclusion_page.path_names.full as path_name %}
        <div id="cpDiv" class="container">
          <div class="row">
            <div class="col-sm-1">
              have a column of small thumbnails here
              Use the pathnames somehow to create a vertical carousel of images
              Need to size the images in some way, too

            </div>
            <div class="col-sm-8">
              <!-- image of conclusion page -->
              <img src="{% static path_name %}" alt="Full conclusion page from study {{conclusion_page.study}} on platform {{conclusion_page.platform}}." width="100%" />
            </div>
            <div class="col-sm-3">
              <!-- INFO -->
              <p><strong>Platform: </strong>{{conclusion_page.platform}}</p>
              <p><strong>Study: </strong>{{conclusion_page.study}}</p>
              <p><strong>Blocks used: </strong>should this have links to all the blocks??</p>
              <ul>
                <li><em>Block 1: </em>Explanation/benefits</li>
                <li><em>Block 2: </em>Explanation/benefits</li>
              </ul>
              <p><strong>Other comments: </strong>Quote or something from researcher?</p>
            </div>
          </div>
          <div class="clearfix">
              Do something here
          </div>
        </div>
      {% endwith %}
    {% endif %}
  </div>
</body>

digestif/templates/digestif/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'digestif/index.css' %}">
    <script>
      function updateLikes() {
        like_count = window.localStorage.getItem('likeCount');
        if (like_count == null) {
          like_count = 0;
        }
        document.getElementById('likeCount').innerHTML = like_count;
      }
    </script>
    <title>Digestif</title>
</head>
<body onload="updateLikes()">
  <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'digestif:index' %}" style="color: orange">digestif</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
              <!-- <a class="nav-link" href="./explore.html">Explore</a> -->
              <a class="nav-link" href="{% url 'digestif:explore' %}">Explore</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'digestif:create' %}">Create</a>
              <!-- <a class="nav-link" href="./create.html">Create</a> -->
          </li>
      </ul>
      <div class="navbar-text">
         <!-- <p><span>&#9829; <span id="likeCount">0</span></span></p> -->
         <button type="button" class="btn btn-primary" style="background-color: rgb(204, 68, 74); border-style: none">
            You've &#9829;'d <span id="likeCount" class="badge badge-light">0</span> blocks!
          </button>
      </div>
    </div>
  </nav>
  <div style="height:25px;"></div>

  <div class="container" style="margin-bottom: 50px;">
    <div class="row align-items-center">
      <div class="col">
        <h1 style="color: orange;">digestif</h1>
        <p class="text-muted">[dee-zhe-<span class="font-weight-bold">steef</span>] (noun)<br/>a tool that supports scientific outreach and participant learning in online experiments</p>
        <p>Researchers conduct large-scale online experiments for more diverse and large samples.</p>
        <p>To do scientific outreach, iterate on experimental design, improve data quality, and attract more participants, researchers use <span class="font-italic font-weight-bold">digestif pages</span>.</p>
        <p>Digestif pages are at the end of online experiments and help participants learn and make sense of how they have just contributed to cutting edge research.</p>
        <p>Explore our library of digestif pages from popular platforms, or create and download your own.</p>
        <a role="button" class="btn btn-outline-warning btn-lg" href="{% url 'digestif:explore' %}">Explore</a>
        <a role="button" class="btn btn-outline-warning btn-lg" href="{% url 'digestif:create' %}">Create</a>
      </div>
      <div class="col">

        <div id="digestifCarousel" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#digestifCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#digestifCarousel" data-slide-to="1"></li>
            <li data-target="#digestifCarousel" data-slide-to="2"></li>
            <li data-target="#digestifCarousel" data-slide-to="3"></li>
            <li data-target="#digestifCarousel" data-slide-to="4"></li>
            <li data-target="#digestifCarousel" data-slide-to="5"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <div class="carousel-caption">
                <h3>Marketing</h3>
                <p>Digestif pages that allow participants to share their personalized results lead to snowball recruitment.</p>
              </div>
              <img class="d-block w-100" src="../../static/digestif/index/marketing.png" alt="Sketch of marketing">
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="../../static/digestif/index/dataQuality.png" alt="Sketch about data quality">
              <div class="carousel-caption">
                <h3>Data Quality</h3>
                <p>The information promised on digestif pages can incentivize participants to contribute more honest data rather than game the study.</p>
              </div>
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="../../static/digestif/index/feedback.png" alt="Sketch about participants giving researchers feedback that researchers incorporate">
              <div class="carousel-caption">
                <h3>Feedback</h3>
                <p>The feedback participants give on digestif pages or give via email helps researchers identify technical bugs and language that is difficult to understand.</p>
              </div>
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="../../static/digestif/index/debrief.png" alt="Sketch about debriefing">
              <div class="carousel-caption">
                <h3>Debrief</h3>
                <p>Participants are curious about how what they do contributes to science. Researchers have an opportunity to explain the implications of their research on digestif pages.</p>
              </div>
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="../../static/digestif/index/ethics.png" alt="Sketch of ethics scale">
              <div class="carousel-caption">
                <h3>Ethics</h3>
                <p>One way researchers can keep participants informed and respect their time and effort is to provide participants with information about the nature of the online study and research.</p>
              </div>
            </div>
            <div class="carousel-item">
              <img class="d-block w-100" src="../../static/digestif/index/outreach.png" alt="Sketch about outreach that is symbolized by a megaphone called Science">
              <div class="carousel-caption">
                <h3>Outreach</h3>
                <p>Giving participants additional information on the digestif pages about research aims and findings is a form of scientific outreach that reaches a population different from other forms of outreach and online learning.</p>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#digestifCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#digestifCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="container-fluid" style="background-color: rgb(255, 249, 234);">
  <div class="container">
    <div class="row" style="padding-top: 50px;">
      <h1 class="mx-auto" style="color: orange;">The Building Blocks of a Conclusion Page</h1>
      <p class="mx-auto text-muted">All the blocks are optional. Researchers can choose based on their participants and goals.</p>
    </div>
    <div class="row" style="padding-top: 50px; padding-bottom: 50px;">
      <div class="col">
        <div class="alert" style="background-color: white;">
          <h5>Acknowledgments</h5>
          <p>Acknowledgement blocks thank participants for their time and data contribution.</p>
        </div>
        <div class="alert" style="background-color: white;">
          <h5>Experimental Design</h5>
          <p>Experimental design blocks tell participants why the online experiment was designed the way it was. These blocks can also explain how any personalized results were generated and the limitations of the study.</p>
        </div>
        <div class="alert" style="background-color: white;">
          <h5>Feedback</h5>
          <p>Feedback blocks allow participants to provide suggestions, ideas, and concerns about the tasks. Based on the feedback, researchers can refine their studies iteratively.</p>
        </div>
        <div class="alert" style="background-color: white;">
          <h5>Other Studies</h5>
          <p>Other studies blocks contain links to other studies on a platform, leveraging current traffic to attract more participation to other studies.</p>
        </div>
        <div class="alert" style="background-color: white;">
          <h5>Personalized Results</h5>
          <p>Personalized results blocks provide participants some insight into their performance/data. A common form of personalized results is to compare a participant's performance with the performance of other participants or groups already found in previous research (social comparison). The promise of personalized results is often used to advertise studies.</p>
        </div>
        <div class="alert" style="background-color: white;">
          <h5>Previous Research</h5>
          <p>Previous research blocks allow researchers to share about their fields and previous research findings.</p>
        </div>
        <div class="alert" style="background-color: white;">
          <h5>Research Goals</h5>
          <p>Research goals blocks explain how the results of the study will contribute to advancing various disciplines or improving applications (e.g., possible products, etc.).</p>
        </div>
        <div class="alert" style="background-color: white;">
          <h5>Research Motivations</h5>
          <p>Research motivations blocks tell participants why data is being collected and/or the hypotheses that the study addresses.</p>
        </div>
        <div class="alert" style="background-color: white;">
          <h5>Share</h5>
          <p>Share blocks allow participants to share their participation on social media, which can generate traffic for the study.</p>
        </div>
        <div class="alert" style="background-color: white;">
          <h5>Community Building</h5>
          <p>Community building blocks enable participants to connect with researchers and researchers to build longer-term relationships with participants. Example block functionalities include joining a mailing list or liking a study platform on social media.</p>
        </div>
        <div class="row" style="padding-top: 50px;">
          <h4 class="mx-auto"><a href="{% url 'digestif:explore' %}">See examples.</a></h4>
        </div>
      </div>
    </div>
  </div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
</html>